/** Mirrors candidate portal Profile for form-built CVs. */
export type FormProfile = {
  name: string;
  headline: string;
  email: string;
  phone: string;
  city: string;
  state: string;
  avatar: string;
  verified: boolean;
  completeness: number;
  role: string;
  registrationNumber: string;
  registrationCouncil: string;
  specialty?: string;
  grade?: string;
  preferredRoleTypes?: string[];
  licenseStatus?: string;
  specialistRegisterStatus?: string;
  revalidationDate?: string;
  indemnityProvider?: string;
  rightToWork?: string;
  visaStatus?: string;
  yearsExperience: number;
  summary: string;
  qualifications: { degree: string; institution: string; year: string }[];
  experience: {
    role: string;
    hospital: string;
    city: string;
    start: string;
    end: string;
    summary: string;
    current?: boolean;
    specialty?: string;
    hospitalType?: string;
    department?: string;
    patientLoad?: string;
    rota?: string;
    keyProcedures?: string[];
  }[];
  clinicalSkills: string[];
  technicalSkills: string[];
  procedures: { name: string; count: number }[];
  certifications: { name: string; issuer: string; year: string }[];
  publications: string[];
  publicationDetails?: {
    title: string;
    authors: string;
    journal: string;
    year: string;
    doi: string;
    citations: number;
  }[];
  totalCitations?: string;
  hIndex?: string;
  i10Index?: string;
  scholarUrl?: string;
  orcid?: string;
  professionalHighlights?: {
    category: string;
    title: string;
    detail: string;
    year: string;
  }[];
  languages: string[];
  availability: string;
  expectedSalaryMin: number;
  expectedSalaryMax: number;
  documentChecklist?: string[];
  supportingDocuments?: any[];
};
