/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImpersonateRouteImport } from './routes/impersonate'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthOnboardingRouteImport } from './routes/auth.onboarding'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthInviteRouteImport } from './routes/auth.invite'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppJobsRouteImport } from './routes/_app.jobs'
import { Route as AppApplicantsRouteImport } from './routes/_app.applicants'
import { Route as AppJobsIndexRouteImport } from './routes/_app.jobs.index'
import { Route as AppJobsNewRouteImport } from './routes/_app.jobs.new'
import { Route as AppJobsJobIdIndexRouteImport } from './routes/_app.jobs.$jobId.index'
import { Route as AppJobsJobIdEditRouteImport } from './routes/_app.jobs.$jobId.edit'

const ImpersonateRoute = ImpersonateRouteImport.update({
  id: '/impersonate',
  path: '/impersonate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInviteRoute = AuthInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicantsRoute = AppApplicantsRouteImport.update({
  id: '/applicants',
  path: '/applicants',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIndexRoute = AppJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppJobsRoute,
} as any)
const AppJobsNewRoute = AppJobsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppJobsRoute,
} as any)
const AppJobsJobIdIndexRoute = AppJobsJobIdIndexRouteImport.update({
  id: '/$jobId/',
  path: '/$jobId/',
  getParentRoute: () => AppJobsRoute,
} as any)
const AppJobsJobIdEditRoute = AppJobsJobIdEditRouteImport.update({
  id: '/$jobId/edit',
  path: '/$jobId/edit',
  getParentRoute: () => AppJobsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/impersonate': typeof ImpersonateRoute
  '/applicants': typeof AppApplicantsRoute
  '/jobs': typeof AppJobsRouteWithChildren
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/invite': typeof AuthInviteRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/': typeof AuthIndexRoute
  '/jobs/new': typeof AppJobsNewRoute
  '/jobs/': typeof AppJobsIndexRoute
  '/jobs/$jobId/edit': typeof AppJobsJobIdEditRoute
  '/jobs/$jobId/': typeof AppJobsJobIdIndexRoute
}
export interface FileRoutesByTo {
  '/impersonate': typeof ImpersonateRoute
  '/applicants': typeof AppApplicantsRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/invite': typeof AuthInviteRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/signup': typeof AuthSignupRoute
  '/': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/jobs/new': typeof AppJobsNewRoute
  '/jobs': typeof AppJobsIndexRoute
  '/jobs/$jobId/edit': typeof AppJobsJobIdEditRoute
  '/jobs/$jobId': typeof AppJobsJobIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/impersonate': typeof ImpersonateRoute
  '/_app/applicants': typeof AppApplicantsRoute
  '/_app/jobs': typeof AppJobsRouteWithChildren
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/invite': typeof AuthInviteRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_app/jobs/new': typeof AppJobsNewRoute
  '/_app/jobs/': typeof AppJobsIndexRoute
  '/_app/jobs/$jobId/edit': typeof AppJobsJobIdEditRoute
  '/_app/jobs/$jobId/': typeof AppJobsJobIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/impersonate'
    | '/applicants'
    | '/jobs'
    | '/search'
    | '/settings'
    | '/auth/forgot-password'
    | '/auth/invite'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/signup'
    | '/auth/'
    | '/jobs/new'
    | '/jobs/'
    | '/jobs/$jobId/edit'
    | '/jobs/$jobId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/impersonate'
    | '/applicants'
    | '/search'
    | '/settings'
    | '/auth/forgot-password'
    | '/auth/invite'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/signup'
    | '/'
    | '/auth'
    | '/jobs/new'
    | '/jobs'
    | '/jobs/$jobId/edit'
    | '/jobs/$jobId'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/impersonate'
    | '/_app/applicants'
    | '/_app/jobs'
    | '/_app/search'
    | '/_app/settings'
    | '/auth/forgot-password'
    | '/auth/invite'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/signup'
    | '/_app/'
    | '/auth/'
    | '/_app/jobs/new'
    | '/_app/jobs/'
    | '/_app/jobs/$jobId/edit'
    | '/_app/jobs/$jobId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ImpersonateRoute: typeof ImpersonateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/impersonate': {
      id: '/impersonate'
      path: '/impersonate'
      fullPath: '/impersonate'
      preLoaderRoute: typeof ImpersonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/onboarding': {
      id: '/auth/onboarding'
      path: '/onboarding'
      fullPath: '/auth/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/invite': {
      id: '/auth/invite'
      path: '/invite'
      fullPath: '/auth/invite'
      preLoaderRoute: typeof AuthInviteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applicants': {
      id: '/_app/applicants'
      path: '/applicants'
      fullPath: '/applicants'
      preLoaderRoute: typeof AppApplicantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/': {
      id: '/_app/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AppJobsIndexRouteImport
      parentRoute: typeof AppJobsRoute
    }
    '/_app/jobs/new': {
      id: '/_app/jobs/new'
      path: '/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AppJobsNewRouteImport
      parentRoute: typeof AppJobsRoute
    }
    '/_app/jobs/$jobId/': {
      id: '/_app/jobs/$jobId/'
      path: '/$jobId'
      fullPath: '/jobs/$jobId/'
      preLoaderRoute: typeof AppJobsJobIdIndexRouteImport
      parentRoute: typeof AppJobsRoute
    }
    '/_app/jobs/$jobId/edit': {
      id: '/_app/jobs/$jobId/edit'
      path: '/$jobId/edit'
      fullPath: '/jobs/$jobId/edit'
      preLoaderRoute: typeof AppJobsJobIdEditRouteImport
      parentRoute: typeof AppJobsRoute
    }
  }
}

interface AppJobsRouteChildren {
  AppJobsNewRoute: typeof AppJobsNewRoute
  AppJobsIndexRoute: typeof AppJobsIndexRoute
  AppJobsJobIdEditRoute: typeof AppJobsJobIdEditRoute
  AppJobsJobIdIndexRoute: typeof AppJobsJobIdIndexRoute
}

const AppJobsRouteChildren: AppJobsRouteChildren = {
  AppJobsNewRoute: AppJobsNewRoute,
  AppJobsIndexRoute: AppJobsIndexRoute,
  AppJobsJobIdEditRoute: AppJobsJobIdEditRoute,
  AppJobsJobIdIndexRoute: AppJobsJobIdIndexRoute,
}

const AppJobsRouteWithChildren =
  AppJobsRoute._addFileChildren(AppJobsRouteChildren)

interface AppRouteChildren {
  AppApplicantsRoute: typeof AppApplicantsRoute
  AppJobsRoute: typeof AppJobsRouteWithChildren
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApplicantsRoute: AppApplicantsRoute,
  AppJobsRoute: AppJobsRouteWithChildren,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthInviteRoute: typeof AuthInviteRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthInviteRoute: AuthInviteRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ImpersonateRoute: ImpersonateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
